project_id = "wgohndthjgeqamfuldov"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.kenzie-chat]
verify_jwt = false

[functions.verify-admin-key]
verify_jwt = false

[functions.checkdrop-evaluate]
verify_jwt = false

[functions.jotform-webhook]
verify_jwt = false

[functions.checkout-session]
verify_jwt = false

[functions.create-monthly-donation]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.weekly-story-post]
verify_jwt = false
