project_id = "wgohndthjgeqamfuldov"

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-admin-passcode]
verify_jwt = false

[functions.jotform-webhook]
verify_jwt = false

[functions.verify-admin-key]
verify_jwt = false

[functions.checkout-session]
verify_jwt = false

[functions.verify-checkout]
verify_jwt = false

[functions.kenzie-chat]
verify_jwt = false

[functions.help-search]
verify_jwt = false

[functions.help-log]
verify_jwt = false

[functions.checkdrop-evaluate]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-nonprofit-notification]
verify_jwt = false

[functions.send-policy-notification]
verify_jwt = false

[functions.create-monthly-donation]
verify_jwt = false

[functions.weekly-story-post]
verify_jwt = false

[functions.sync-irs-nonprofits]
verify_jwt = false

[functions.bulk-import-nonprofits]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.sinalite-price]
verify_jwt = false

[functions.check-live-credentials]
verify_jwt = false
